global using MapElements;
global using MapSystem;
global using GameSystem;
global using Utility;
global using InventorySystem;
global using UI_System;
global using SceneSystem;
global using PuzzleSystem;
global using PlayerSystem;
global using EnemySystem;
global using static Utility.RNG;
global using static MapElements.ElementsIdentifiers;
global using static EnemySystem.EnemiesLibrary;
global using static MapSystem.DecorLibrary;
